import pandas as pd
from pandas.tseries.offsets import CustomBusinessDay
from pandas.tseries.holiday import USFederalHolidayCalendar
from datetime import datetime, timedelta
import matplotlib.pyplot as plt

def calculate_lookback_date(ticker, target_date_str, lookback_days=22):
    """
    Routes the date calculation based on asset class to ensure 
    lookback periods align with actual trading days.
    """
    target_date = pd.to_datetime(target_date_str)
    
    crypto_identifiers = ['BTC', 'ETH', 'SOL', '-USD']
    is_crypto = any(crypto in ticker.upper() for crypto in crypto_identifiers)
    
    if is_crypto:
        start_date_init = target_date - timedelta(days=lookback_days)
        asset_class = "Crypto"
    else:
        us_trading_days = CustomBusinessDay(calendar=USFederalHolidayCalendar())
        start_date_init = target_date - (lookback_days * us_trading_days)
        asset_class = "Equity"
        
    return start_date_init, asset_class

def lake_read_parquet(data_path, start_date=None, end_date=None):
    insights_df = pd.read_parquet(data_path, engine='pyarrow')
    insights_df['Date'] = pd.to_datetime(insights_df['Date'])
    insights_df.set_index('Date', inplace=True)

    if not start_date and not end_date:
        return insights_df
    elif not end_date:
        return insights_df[insights_df.index >= start_date]
    else:
        return insights_df[(insights_df.index >= start_date) & (insights_df.index <= end_date)]

def plot_equity_curve(df, ticker):
    """Visualizes the backtest using the DatetimeIndex."""
    plt.figure(figsize=(12, 6))
    
    # Replaced df['Date'] with df.index
    plt.plot(df.index, df['Asset_Equity'], label='Buy & Hold', color='gray', alpha=0.7)
    plt.plot(df.index, df['Strategy_Equity'], label='RSI 35/65 Strategy', color='blue', linewidth=2)
    
    plt.title(f'{ticker} - Baseline Strategy Equity Curve')
    plt.xlabel('Date')
    plt.ylabel('Cumulative Return (1.0 = 100%)')
    plt.legend()
    plt.grid(alpha=0.3)
    plt.show()

def plot_signals(df, ticker):
    """
    Plots the asset price, moving averages, and overlays the exact 
    Buy (Green ^) and Sell (Red v) signals generated by the strategy.
    """
    plt.figure(figsize=(14, 7))

    # Plot the Main Price Line
    plt.plot(df.index, df['Adj Close'], label='Price', color='black', alpha=0.5, linewidth=1.5)

    # Plot the Moving Averages

    plt.plot(df.index, df['SMA_20'], label='SMA 20', color='blue', alpha=0.6, linestyle='--')
    plt.plot(df.index, df['SMA_50'], label='SMA 50', color='orange', alpha=0.6, linestyle='--')

    # Pinpoint the exact Trade Execution days
    changes = df['Position'].diff()
    buy_signals = df[changes == 1]
    sell_signals = df[changes == -1]

    # Overlay the Signal Arrows
    # marker='^' is an up arrow, 'v' is a down arrow.
    # zorder=5 forces the arrows to render on top of the price lines.
    plt.scatter(buy_signals.index, buy_signals['Adj Close'], 
                marker='^', color='green', label='Buy Signal', s=120, zorder=5)
    
    plt.scatter(sell_signals.index, sell_signals['Adj Close'], 
                marker='v', color='red', label='Sell Signal', s=120, zorder=5)

    # Make it look professional
    plt.title(f'{ticker} - Strategy Executions & Moving Averages', fontsize=14)
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.legend(loc='best')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

import matplotlib.pyplot as plt

def plot_montage(df, ticker):
    """
    Creates a side-by-side montage dashboard.
    Left panel: Price, Moving Averages, and Signals.
    Right panel: The resulting Equity Curve.
    """
    # 1 row, 2 columns for a side-by-side layout. 
    # Expanded width to 18 to give both charts room to breathe.
    fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, figsize=(18, 6))

    # ==========================================
    # LEFT PANEL: Price & Signals
    # ==========================================
    ax1.plot(df.index, df['Adj Close'], label='Price', color='black', alpha=0.5, linewidth=1.5)

    if 'SMA_20' in df.columns:
        ax1.plot(df.index, df['SMA_20'], label='SMA 20', color='blue', alpha=0.6, linestyle='--')
    if 'SMA_50' in df.columns:
        ax1.plot(df.index, df['SMA_50'], label='SMA 50', color='orange', alpha=0.6, linestyle='--')

    changes = df['Position'].diff()
    buy_signals = df[changes == 1]
    sell_signals = df[changes == -1]

    ax1.scatter(buy_signals.index, buy_signals['Adj Close'], 
                marker='^', color='green', label='Buy Signal', s=100, zorder=5)
    ax1.scatter(sell_signals.index, sell_signals['Adj Close'], 
                marker='v', color='red', label='Sell Signal', s=100, zorder=5)

    ax1.set_title(f'{ticker} - Price & Signals', fontsize=14)
    ax1.set_ylabel('Price')
    ax1.legend(loc='upper left')
    ax1.grid(True, alpha=0.3)
    ax1.tick_params(axis='x', rotation=45) # Tilts dates to prevent overlap

    # ==========================================
    # RIGHT PANEL: Equity Curve
    # ==========================================
    ax2.plot(df.index, df['Asset_Equity'], label='Buy & Hold', color='gray', alpha=0.7)
    ax2.plot(df.index, df['Strategy_Equity'], label='Strategy Equity', color='blue', linewidth=2)

    ax2.set_title('Cumulative Return (1.0 = 100%)', fontsize=14)
    ax2.set_ylabel('Equity Multiplier')
    ax2.legend(loc='upper left')
    ax2.grid(True, alpha=0.3)
    ax2.tick_params(axis='x', rotation=45)

    # Clean up the layout
    plt.tight_layout()
    plt.show()